version: '3'
services:
  test:
    build: .
    environment:
      - INFLUX_URL=http://influxdb:8086
      - ORA_CONNECT_STRING=oracle:1521/XE
      - PORT=8082
    ports:
      - "8082:8082"
  influxdb:
    image: influxdb:latest
    ports:
      - "8083:8083"
      - "8086:8086"
      - "8090:8090"
  oracle:
    image: docker.pkg.github.com/navikt/fpsak-setup/fpsak-oracle:v20190708
    shm_size: 1gb
    ports:
      - "1521:1521"

