version: '3'
services:
  test:
    build: .
    environment:
      - INFLUX_URL=http://influxdb:8086
      - ORA_CONNECT_STRING=oracle:1521/xe
      - PORT=8082
    ports:
      - "8082:8082"
  influxdb:
    image: influxdb:latest
    ports:
      - "8083:8083"
      - "8086:8086"
  oracle:
    image: wnameless/oracle-xe-11g-r2
    ports:
      - 1522:1521
    environment:
      #- ORACLE_ALLOW_REMOTE=true
      - ORACLE_DISABLE_ASYNCH_IO=true

