version: 2
jobs:
  build:
    docker:
      - image: collinestes/docker-node-oracle:latest

      # https://circleci.com/docs/2.0/google-auth/#authorizing-the-google-cloud-sdk
      - image: eu.gcr.io/beste-adm/oracle:v20190408
        command: [--shm-size=1g]
        auth:
          username: _json_key
          password: $GCLOUD_SERVICE_KEY

      - image: influxdb:latest

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-
      - run: npm install -g n && n latest
      - run: node -v
      - run: yarn install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      # run tests!
      - run:  yarn test

  deploy:
    docker:
      - image: circleci/node:latest

    working_directory: ~/repo

    steps:
      - checkout
      - run: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" >> ~/.npmrc
      - run: npm publish --access public

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master
