version: 2
jobs:
  build:
    docker:
      - image: collinestes/docker-node-oracle:latest

      - image: docker.pkg.github.com/navikt/fpsak-setup/fpsak-oracle:v20190708
        auth:
          username: $GITHUB_USERNAME
          password: $GITHUB_PASSWORD

      - image: influxdb:latest

    working_directory: ~/repo

    steps:
      - checkout
      - restore_cache: # Download and cache dependencies
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-
      - run: npm install -g n && n lts
      - run: node -v
      - run: yarn install --ignore-optional
      - run: yarn upgrade

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      # run tests!
      - run: yarn test

  deploy:
    docker:
      - image: circleci/node:latest

    working_directory: ~/repo

    steps:
      - checkout
      - run: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" >> ~/.npmrc
      - run: npm publish --access public

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build:
          context: familie-ci
      - deploy:
          context: familie-ci
          requires:
            - build
          filters:
            branches:
              only: master
