# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build:
    docker:
      - image: collinestes/docker-node-oracle:latest

      # https://circleci.com/docs/2.0/google-auth/#authorizing-the-google-cloud-sdk
      - image: eu.gcr.io/beste-adm/oracle:v20190408
        command: [--shm-size=1g]
        auth:
          username: _json_key
          password: $GCLOUD_SERVICE_KEY

      - image: influxdb:latest

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-
      - run: npm install -g n && n latest
      - run: node -v
      - run: yarn install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      # run tests!
      - run:  node ./tests/wait.js
      - run:  node ./tests/seed.js
      - run:  node ./tests/stream.js
